# Generated by Django 5.1.4 on 2025-01-02 16:12

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_poi_rename_cctv_listing_cctv_listing_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
